# Generated by Django 3.1.1 on 2020-10-04 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201004_1033'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professor'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
