# Generated by Django 3.1.1 on 2020-10-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201003_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='date_solved',
            field=models.DateTimeField(null=True),
        ),
    ]
