# Generated by Django 3.1.1 on 2020-10-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201004_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
