# Generated by Django 3.1.1 on 2020-10-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_studentuser_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='school',
            field=models.CharField(default='Harvard', max_length=100),
            preserve_default=False,
        ),
    ]
